# Generated by Django 6.0.3 on 2026-03-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vandal_number', models.IntegerField()),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Uniform_Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_id', models.IntegerField()),
                ('size', models.CharField(max_length=32)),
                ('clothing_type', models.CharField(choices=[('Shako', [('percussion', 'Percussion'), ('horn', 'Horn')]), ('Top', [('white_jacket', 'White Jacket'), ('black_jacket', 'Black Jacket'), ('gritman_jacket', 'Gritman Jacket')]), ('Bottom', [('skirt', 'Skirt'), ('black_pants', 'Black Pants'), ('white_pants', 'White Pants')]), ('gauntlet', 'Gauntlet')], max_length=32)),
            ],
        ),
    ]
