# Generated by Django 6.0.3 on 2026-03-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(max_length=32)),
                ('instrument_id', models.CharField(max_length=32)),
                ('notes', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='uniform_piece',
            name='clothing_type',
        ),
        migrations.AddField(
            model_name='uniform_piece',
            name='notes',
            field=models.CharField(default='N/A', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='vandal_number',
            field=models.CharField(max_length=16),
        ),
    ]
