# Generated by Django 6.0.3 on 2026-03-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_instrument_remove_uniform_piece_clothing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform_piece',
            name='clothing_type',
            field=models.CharField(choices=[('Shako', [('percussion', 'Percussion'), ('horn', 'Horn')]), ('Top', [('white_jacket', 'White Jacket'), ('black_jacket', 'Black Jacket'), ('gritman_jacket', 'Gritman Jacket')]), ('Bottom', [('skirt', 'Skirt'), ('black_pants', 'Black Pants'), ('white_pants', 'White Pants')]), ('gauntlet', 'Gauntlet')], default='N/A', max_length=32),
            preserve_default=False,
        ),
    ]
