# Generated by Django 6.0.3 on 2026-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_uniform_piece_clothing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform_piece',
            name='clothing_type',
            field=models.CharField(choices=[('Shako', [('perc_shako', 'Percussion Shako'), ('horn_shako', 'Horn Shako')]), ('Top', [('white_jacket', 'White Jacket'), ('black_jacket', 'Black Jacket'), ('gritman_jacket', 'Gritman Jacket')]), ('Bottom', [('skirt', 'Skirt'), ('black_pants', 'Black Pants'), ('white_pants', 'White Pants')]), ('gauntlet', 'Gauntlet')], max_length=32),
        ),
    ]
