# Generated by Django 6.0.3 on 2026-04-01 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_uniform_piece_clothing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.RemoveField(
            model_name='uniform_piece',
            name='id',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='vandal_number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uniform_piece',
            name='clothing_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Rents_Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.instrument')),
                ('vandal_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vandal_number', 'instrument_id'), name='unique_instrument_rental')],
            },
        ),
        migrations.CreateModel(
            name='Rents_Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.uniform_piece')),
                ('vandal_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vandal_number', 'uniform_id'), name='unique_uniform_rental')],
            },
        ),
    ]
