# Generated by Django 6.0.3 on 2026-04-02 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_instrument_id_remove_member_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rents_instrument',
            name='unique_instrument_rental',
        ),
        migrations.RemoveConstraint(
            model_name='rents_uniform',
            name='unique_uniform_rental',
        ),
        migrations.AlterField(
            model_name='rents_instrument',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.instrument'),
        ),
        migrations.AlterField(
            model_name='rents_uniform',
            name='uniform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.uniform_piece'),
        ),
        migrations.RemoveField(
            model_name='rents_instrument',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rents_uniform',
            name='id',
        ),
    ]
